/**
 * The diff engine: compares a remote canonical document against the locally
 * edited one and produces ONLY server-whitelisted JSON Patch operations.
 *
 * Identity-based: items are matched by `id` then `name` (see `matchItems`),
 * never by index. Renames are plain `replace .../name` ops because children
 * are always addressed by the REMOTE item's key (stable across edits).
 * Emission order per domain: adds (parents first) → replaces → removes.
 */

import type { KeyedArrayRule, Rule } from './patch-rules';
import type { LayoutDomain, PlannedOp } from './types';

import { isDeepStrictEqual } from 'util';
import { v4 as uuidv4 } from 'uuid';

import { DOMAIN_RULES, matchesWhitelist } from './patch-rules';
import { LayoutFileError } from './yaml-file';

export type DiffResult = {
  ops: PlannedOp[];
  warnings: string[];
};

type Item = Record<string, unknown>;

/** Address segment for an item: prefer the stable id, else a path-safe name. */
function addressOf(item: Item, yamlPath: string): string {
  if (item.id !== undefined && item.id !== null) return String(item.id);

  const { name } = item;
  if (typeof name === 'string' && /^[^\s/:]+$/.test(name)) return name;

  throw new LayoutFileError(
    `${yamlPath}: item without a usable \`id\` (and the name contains characters forbidden in a path). ` +
      'Do not remove the `id` fields generated by `forest layout pull`.',
  );
}

/** Identity key used to match local and remote items. */
function identityOf(item: Item): string | undefined {
  if (item.id !== undefined && item.id !== null) return `id:${String(item.id)}`;
  if (typeof item.name === 'string') return `name:${item.name}`;

  return undefined;
}

type ItemMatch = {
  added: Item[];
  common: Array<{ local: Item; remote: Item }>;
  removed: Item[];
};

/**
 * Match local items to remote ones by `id`, then by `name` — so a hand-authored
 * item that omits its `id` updates the existing element instead of being seen as
 * an add + a remove. Fails loudly on ambiguous input (duplicate local identities,
 * or two locals resolving to the same remote).
 */
function matchItems(remoteItems: Item[], localItems: Item[], yamlPath: string): ItemMatch {
  const remoteById = new Map<string, Item>();
  const remoteByName = new Map<string, Item>();
  remoteItems.forEach(item => {
    if (item.id !== undefined && item.id !== null) remoteById.set(String(item.id), item);
    if (typeof item.name === 'string') remoteByName.set(item.name, item);
  });

  const seen = new Set<string>();
  const matched = new Set<Item>();
  const added: Item[] = [];
  const common: Array<{ local: Item; remote: Item }> = [];

  localItems.forEach(local => {
    const key = identityOf(local);
    if (key === undefined) {
      throw new LayoutFileError(
        `${yamlPath}: item without \`id\` or \`name\` — unable to identify it.`,
      );
    }
    if (seen.has(key)) {
      throw new LayoutFileError(`${yamlPath}: two items share the same identity (${key}).`);
    }
    seen.add(key);

    const remote =
      (local.id !== undefined && local.id !== null && remoteById.get(String(local.id))) ||
      (typeof local.name === 'string' && remoteByName.get(local.name)) ||
      undefined;

    if (!remote) {
      added.push(local);
    } else if (matched.has(remote)) {
      throw new LayoutFileError(
        `${yamlPath}: two items resolve to the same remote element (\`id\`/\`name\` collision).`,
      );
    } else {
      matched.add(remote);
      common.push({ local, remote });
    }
  });

  return { added, common, removed: remoteItems.filter(item => !matched.has(item)) };
}

function short(value: unknown): string {
  if (value === null) return 'null';
  if (value === undefined) return '∅';
  if (typeof value === 'object') {
    const { name } = value as Item;
    if (typeof name === 'string') return `{ name: « ${name} », … }`;

    return Array.isArray(value) ? `[${value.length} items]` : '{…}';
  }

  const text = typeof value === 'string' ? `« ${value} »` : String(value);

  return text.length > 60 ? `${text.slice(0, 57)}…` : text;
}

type Bucket = {
  adds: PlannedOp[];
  removes: PlannedOp[];
  replaces: PlannedOp[];
  warnings: string[];
};

type Context = {
  bucket: Bucket;
  domain: LayoutDomain;
  pathPrefix: string;
  premiumPack?: string;
  yamlPrefix: string;
};

function emit(ctx: Context, kind: keyof Omit<Bucket, 'warnings'>, op: PlannedOp): void {
  ctx.bucket[kind].push(op);
}

function diffScalarLike(
  ctx: Context,
  rule: Rule & { premiumPack?: string; prop: string; removable?: boolean },
  remote: Item,
  local: Item,
): void {
  const path = `${ctx.pathPrefix}/${rule.prop}`;
  const yamlPath = `${ctx.yamlPrefix}.${rule.prop}`;
  const remoteValue = remote[rule.prop];
  const localValue = local[rule.prop];

  if (isDeepStrictEqual(remoteValue, localValue)) return;

  const premiumPack = rule.premiumPack ?? ctx.premiumPack;

  // Absent locally = "leave alone" (partial-authoring / patch semantics): the
  // file need not carry every field. To clear a value, set it explicitly to
  // `null` (which reaches the replace path below as a value, not `undefined`).
  if (localValue === undefined) return;

  emit(ctx, 'replaces', {
    domain: ctx.domain,
    label: `${yamlPath}: ${short(remoteValue)} → ${short(localValue)}`,
    op: 'replace',
    path,
    premiumPack,
    value: localValue,
    yamlPath,
  });
}

/**
 * Build the value sent in an `add` op. The server requires a client-supplied
 * `id` on add (PRIMARY_KEYS) — so we KEEP the local id (stable across re-apply
 * and cross-env copies) and generate a uuid only when none is present. Any
 * per-rule `stripOnAdd` keys and `undefined` values are dropped; remaining
 * write-required defaults are filled by {@link fillAddDefaults}.
 */
function prepareAddValue(item: Item, rule: KeyedArrayRule): Item {
  const cleaned: Item = {};
  Object.entries(item).forEach(([key, value]) => {
    if (rule.stripOnAdd?.includes(key)) return;
    if (value === undefined) return;
    cleaned[key] = value;
  });

  if (cleaned.id === undefined || cleaned.id === null) cleaned.id = uuidv4();

  return rule.addDefaults ? rule.addDefaults(cleaned) : cleaned;
}

function diffKeyedArray(
  ctx: Context,
  rule: KeyedArrayRule,
  remoteItems: Item[],
  localItems: Item[],
): void {
  const arrayPath = rule.segment ? `${ctx.pathPrefix}/${rule.segment}` : ctx.pathPrefix;
  const yamlPath = rule.prop ? `${ctx.yamlPrefix}.${rule.prop}` : ctx.yamlPrefix;
  const premiumPack = rule.premiumPack ?? ctx.premiumPack;

  const { added, common, removed } = matchItems(remoteItems, localItems, yamlPath);

  if (rule.fallbackReplaceWhole && (added.length > 0 || removed.length > 0)) {
    emit(ctx, 'replaces', {
      domain: ctx.domain,
      label: `${yamlPath}: replacing the array (${localItems.length} items)`,
      op: 'replace',
      path: arrayPath,
      premiumPack,
      value: localItems,
      yamlPath,
    });

    return;
  }

  added.forEach(item => {
    if (!rule.addable) {
      ctx.bucket.warnings.push(
        `${yamlPath}: cannot add « ${String(
          item.name ?? item.id,
        )} » (items defined by the agent schema).`,
      );

      return;
    }

    emit(ctx, 'adds', {
      domain: ctx.domain,
      label: `${yamlPath}: adding ${short(item)}`,
      op: 'add',
      path: `${arrayPath}/-`,
      premiumPack,
      value: prepareAddValue(item, rule),
      yamlPath,
    });
  });

  removed.forEach(item => {
    if (!rule.removable) {
      ctx.bucket.warnings.push(
        `${yamlPath}: cannot remove « ${String(
          item.name ?? item.id,
        )} » (items defined by the agent schema).`,
      );

      return;
    }

    emit(ctx, 'removes', {
      domain: ctx.domain,
      label: `${yamlPath}: removing ${short(item)}`,
      op: 'remove',
      path: `${arrayPath}/${addressOf(item, yamlPath)}`,
      premiumPack,
      yamlPath,
    });
  });

  common.forEach(({ local, remote }) => {
    const address = addressOf(remote, yamlPath);
    const childCtx: Context = {
      ...ctx,
      pathPrefix: `${arrayPath}/${address}`,
      premiumPack,
      yamlPrefix: `${yamlPath}[${address}]`,
    };
    // eslint-disable-next-line no-use-before-define -- applyRules and diffKeyedArray are mutually recursive
    applyRules(childCtx, rule.children, remote, local);
  });
}

function applyRules(ctx: Context, rules: Rule[], remote: Item, local: Item): void {
  rules.forEach(rule => {
    switch (rule.kind) {
      case 'keyedArray': {
        const remoteItems = (rule.prop ? remote[rule.prop] : remote) as Item[] | undefined;
        const localItems = (rule.prop ? local[rule.prop] : local) as Item[] | undefined;
        diffKeyedArray(ctx, rule, remoteItems ?? [], localItems ?? []);
        break;
      }

      case 'object': {
        const remoteChild = (remote[rule.prop] ?? {}) as Item;
        const localChild = (local[rule.prop] ?? {}) as Item;
        applyRules(
          {
            ...ctx,
            pathPrefix: `${ctx.pathPrefix}/${rule.segment}`,
            yamlPrefix: `${ctx.yamlPrefix}.${rule.prop}`,
          },
          rule.children,
          remoteChild,
          localChild,
        );
        break;
      }

      case 'opaque':
      case 'scalar': {
        diffScalarLike(ctx, rule, remote, local);
        break;
      }

      default:
        break;
    }
  });
}

/** Diff one domain; returns whitelisted ops (adds → replaces → removes) + warnings. */
export function diffDomain(domain: LayoutDomain, remote: unknown, local: unknown): DiffResult {
  const bucket: Bucket = { adds: [], removes: [], replaces: [], warnings: [] };
  const ctx: Context = { bucket, domain, pathPrefix: '', yamlPrefix: domain };

  applyRules(ctx, DOMAIN_RULES[domain].root, (remote ?? {}) as Item, (local ?? {}) as Item);

  const ops = [...bucket.adds, ...bucket.replaces, ...bucket.removes];

  const offending = ops.find(op => !matchesWhitelist(domain, op));
  if (offending) {
    throw new Error(
      `Internal bug: op generated outside the whitelist (${offending.op} ${offending.path}). ` +
        'Please report this case — nothing was sent.',
    );
  }

  return { ops, warnings: bucket.warnings };
}
