version: '3.4'
services:
  MongoDB-MIN:
    image: mongo:3.2
    container_name : forestadmin_test_toolbelt_mongo_min
    ports:
      - "27015:27017"

  MongoDB-MAX:
    image: mongo:4.2
    container_name : forestadmin_test_toolbelt_mongo_max
    ports:
      - "27016:27017"

  PostgreSQL-MIN:
    image : postgres:9.4
    container_name : forestadmin_test_toolbelt_postgres_min
    ports :
      - "54368:5432"
    environment:
      - POSTGRES_DB=forestadmin_test_toolbelt-sequelize
      - POSTGRES_USER=forest
      - POSTGRES_PASSWORD=secret

  PostgreSQL-MAX:
    image : postgres:12.2
    container_name : forestadmin_test_toolbelt_postgres_max
    ports :
      - "54369:5432"
    environment:
      - POSTGRES_DB=forestadmin_test_toolbelt-sequelize
      - POSTGRES_USER=forest
      - POSTGRES_PASSWORD=secret

  MySQL-MIN:
    image: mysql:5.6
    container_name: forestadmin_test_toolbelt_mysql_min
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: forestadmin_test_toolbelt-sequelize
      MYSQL_USER: forest
      MYSQL_PASSWORD: secret
    ports:
      - "127.0.0.1:8998:3306"

  MySQL-MAX:
    image: mysql:8.0
    container_name: forestadmin_test_toolbelt_mysql_max
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: forestadmin_test_toolbelt-sequelize
      MYSQL_USER: forest
      MYSQL_PASSWORD: secret
    ports:
      - "127.0.0.1:8999:3306"

  MS-SQL-MIN:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: forestadmin_test_toolbelt_mssql_min
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "forest2019:"
    ports:
      - "1431:1433"

  MS-SQL-MAX:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: forestadmin_test_toolbelt_mssql_max
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "forest2019:"
    ports:
      - "1432:1433"
