name: Build and Test

on:
  push:
    branches: ["main"]
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      CC_TEST_REPORTER_ID:
        required: true

env:
  CHECKOUT_REF: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous running workflows
        uses: fkirc/skip-duplicate-actions@f75dd6564bb646f95277dc8c3b80612e46a4a1ea
      - uses: actions/checkout@v2.x
        with:
          ref: ${{ env.CHECKOUT_REF }}
          fetch-depth: 0
      - uses: actions/setup-node@v2.x
        with:
          node-version: 14.17.6
      - uses: actions/cache@v2.x
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive --production=false
      - name: Lint commit message
        uses: wagoid/commitlint-github-action@2d572ed5ea8b369af534fa21eea186a7eef07cda
      - name: lint Javascript
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        node: [10, 14]
        include:
          - node: 14
            withCoverage: ${{ true }}
    steps:
      - uses: actions/checkout@v2.x
        with:
          ref: ${{ env.CHECKOUT_REF }}
      - uses: actions/setup-node@v2.x
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        uses: actions/cache@v2.x
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Login on dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Start docker container
        run: docker-compose up -d; sleep 15
      - name: Test with Node ${{ matrix.node }}
        if: ${{ !matrix.withCoverage }}
        run: yarn test
      - name: Test with Node ${{ matrix.node }} & Send coverage
        uses: paambaati/codeclimate-action@84cea27117a473d605400ca3a97fcef7e433e2d6
        if: matrix.withCoverage && matrix.node == 14
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:coverage
      - name: Test prepack
        run: yarn prepack
      - name: Test postpack
        run: yarn postpack
