name: Dispatch workflow 
on:
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  pull_request_target:
    branches:
      - 'dependabot/**'
  workflow_dispatch:

permissions: read-all

jobs:
  dispatch:
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') || 
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || 
      github.event_name == 'workflow_dispatch'
    name: Dispatch event ${{ github.event_name }} from ${{ github.actor }}
    uses: ForestAdmin/toolbelt/.github/workflows/build.yml@chore/workflows
    with:
      secrets:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}