name: Dispatch workflow 
on:
  pull_request:
  pull_request_target:
  workflow_dispatch:

permissions: read-all

jobs:
  get-team:
    runs-on: ubuntu-latest
    outputs:
      developers: |
        ${{ github.actor != 'dependabot[bot]' && join(fromJSON(steps.get_devs.outputs.data).*.login,',') || 
        steps.get_dependabot.outputs.data }}
    steps:
      - id: get_devs
        if: github.actor != 'dependabot[bot]'
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/teams/{team_slug}/members
          org: ForestAdmin
          team_slug: Developers
          role: all
          per_page: 50
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - id: get_dependabot
        if: github.actor == 'dependabot[bot]'
        run: echo "::set-output name=data::dependabot[bot]"
  
  dispatch:
    name: Dispatch event ${{ github.event_name }} from ${{ github.actor }}
    needs: ['get-team']
    if: |
      success() && (
        contains(needs.get-team.outputs.developers, github.actor) ||
        github.event_name == 'workflow_dispatch'
      )
    uses: ForestAdmin/toolbelt/.github/workflows/build.yml@main
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
